name = "domain-filter"
main = "src/index.ts"
compatibility_date = "2024-12-12"

# compatibility_flags = [ "nodejs_compat" ]



# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

workers_dev = false

routes = [
  { pattern = "domain-filter.teco.im", custom_domain = true }
]

[vars]
RESEND_FROM_EMAIL='noreply@zapcal.ai'
RESEND_FROM_NAME='Domain MS'
REGISTROBR_TXT_URL='https://registro.br/dominio/lista-processo-liberacao.txt'
CRON_URL = "https://domain-filter.teco.im/trigger?to=tecoad@gmail.com"

[triggers]
crons = [ "0 12 12 * *" ]